# Generated by Django 5.1.7 on 2025-03-17 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jabatan', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=20, unique=True)),
                ('no_induk_karyawan', models.CharField(max_length=50, unique=True)),
                ('npwp', models.CharField(blank=True, max_length=30, null=True)),
                ('no_bpjs', models.CharField(blank=True, max_length=30, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=15)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('umur', models.IntegerField()),
                ('alamat', models.TextField()),
                ('status_karyawan', models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], default='Aktif', max_length=15)),
                ('tanggal_masuk', models.DateField()),
                ('tanggal_keluar', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DokumenKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kartu_keluarga', models.FileField(blank=True, null=True, upload_to='dokumen/kartu_keluarga/')),
                ('ktp', models.FileField(blank=True, null=True, upload_to='dokumen/ktp/')),
                ('dokumen_sk', models.FileField(blank=True, null=True, upload_to='dokumen/sk/')),
                ('karyawan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sidak_app.karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='AnakKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=15)),
                ('no_telp', models.CharField(blank=True, max_length=20, null=True)),
                ('status_anak', models.CharField(max_length=50)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sidak_app.karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='KontakKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('no_telepon', models.CharField(max_length=20)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('karyawan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sidak_app.karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='SuamiIstri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('pendidikan_terakhir', models.CharField(max_length=100)),
                ('no_telp', models.CharField(max_length=20)),
                ('karyawan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sidak_app.karyawan')),
            ],
        ),
    ]
