# Generated by Django 5.1.7 on 2025-03-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidak_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anakkaryawan',
            name='foto_anak',
            field=models.FileField(blank=True, null=True, upload_to='foto_anak/'),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='foto_profile',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='suamiistri',
            name='foto_suami_istri',
            field=models.FileField(blank=True, null=True, upload_to='profile_suami_istri/'),
        ),
    ]
