# Generated by Django 5.1.7 on 2025-03-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidak_app', '0002_anakkaryawan_foto_anak_karyawan_foto_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='foto_profile',
            field=models.ImageField(blank=True, null=True, upload_to='img/profile/'),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
