# Generated by Django 5.1.7 on 2025-03-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidak_app', '0003_alter_karyawan_foto_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anakkaryawan',
            name='foto_anak',
            field=models.FileField(blank=True, null=True, upload_to='img/foto_anak/'),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='umur',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suamiistri',
            name='foto_suami_istri',
            field=models.FileField(blank=True, null=True, upload_to='img/profile_suami_istri/'),
        ),
    ]
