# Generated by Django 5.1.7 on 2025-03-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidak_app', '0004_alter_anakkaryawan_foto_anak_alter_karyawan_umur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='umur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
