# Generated by Django 5.1.7 on 2025-03-19 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidak_app', '0005_alter_karyawan_umur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anakkaryawan',
            name='foto_anak',
            field=models.ImageField(blank=True, null=True, upload_to='img/foto_anak/'),
        ),
        migrations.AlterField(
            model_name='anakkaryawan',
            name='karyawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anak_list', to='sidak_app.karyawan'),
        ),
        migrations.AlterField(
            model_name='anakkaryawan',
            name='status_anak',
            field=models.CharField(choices=[('Meninggal', 'Meninggal'), ('Hidup', 'Hidup')], default='Kandung', max_length=50),
        ),
    ]
