# Generated by Django 5.1.7 on 2025-03-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidak_app', '0007_alter_anakkaryawan_status_anak'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anakkaryawan',
            options={'ordering': ['anak_ke']},
        ),
        migrations.AlterUniqueTogether(
            name='anakkaryawan',
            unique_together={('karyawan', 'nama', 'tanggal_lahir')},
        ),
        migrations.AddField(
            model_name='anakkaryawan',
            name='anak_ke',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='anakkaryawan',
            name='status_anak',
        ),
    ]
