# Generated by Django 5.1.7 on 2025-03-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidak_app', '0008_alter_anakkaryawan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anakkaryawan',
            name='status_anak',
            field=models.CharField(default='Tidak diketahui', max_length=50),
        ),
    ]
