# Generated by Django 5.1.7 on 2025-03-21 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidak_app', '0009_anakkaryawan_status_anak'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatJabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=100)),
                ('no_sk', models.CharField(max_length=50, unique=True)),
                ('dokumen_sk', models.FileField(blank=True, null=True, upload_to='dokumen/riwayat_jabatan/')),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_akhir', models.DateField(blank=True, null=True)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_jabatan', to='sidak_app.karyawan')),
            ],
            options={
                'ordering': ['-tanggal_mulai'],
            },
        ),
    ]
